name: "Easy release"
description: "Merge branches and publish release in one click"
inputs:
  branch:
    description: "Released branch with commits history"
    default: "main"
    required: true
  slack-channel:
    description: "Slack channel to post message to"
    required: false
outputs:
  release_url:
    description: "Link to release HTML"
runs:
  using: "node20"
  main: "dist/index.js"
